// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htxnkoeervvsrtauiufb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0eG5rb2VlcnZ2c3J0YXVpdWZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwODQ5NjYsImV4cCI6MjA2NzY2MDk2Nn0.gg68nwOXV7wC0OAFEydthF8G3pV-cWxMuNCuc_TW1Gk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});